# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/track_open_instances/all/track_open_instances.rbi
#
# track_open_instances-0.1.15

module TrackOpenInstances
  def self.included(base); end
end
class TrackOpenInstances::OpenInstance
  def creation_stack; end
  def initialize(instance, creation_stack); end
  def instance; end
end
module TrackOpenInstances::ClassMethods
  def add_open_instance(instance); end
  def assert_no_open_instances; end
  def open_instance_count; end
  def open_instances; end
  def open_instances_report; end
  def open_instances_report_body; end
  def open_instances_report_header; end
  def remove_open_instance(instance); end
end
