---
logging:
  level: 'INFO'
  output: 'stdout'

github:
  api_root: 'api.github.com'
  # token: REQUIRED - Set via GCR__GITHUB__TOKEN
  # destination_repo_owner: REQUIRED - Set via GCR__GITHUB__DESTINATION_REPO_OWNER
  # destination_repo_topics_csv: REQUIRED - Set via GCR__GITHUB__DESTINATION_REPO_TOPICS_CSV
  branch_name: 'cookstyle-updates'
  default_git_branch: 'main'
  pull_request:
    title: 'Cookstyle Automated Fixes'
    labels: 'cookstyle,automated'  # Comma-separated
    body_header: "Hey!\nI ran Cookstyle against this repo and here are the results."
    body_topic_template: "This repo was selected due to the topics of %{topics}."

git:
  name: 'Cookstyle Bot'
  email: 'cookstyle-bot@example.com'

changelog:
  location: 'CHANGELOG.md'
  marker: '## Unreleased'
  manage: false  # Boolean (true/false)

cookstyle:
  version_check_regex: 'cookstyle.*'  # Regex to parse `cookstyle --version`
