---
config:
  ul-indent: false  # MD007
  no-multiple-blanks: false  # MD012
  line-length: false  # MD013
  no-duplicate-heading: false  # MD024
  reference-links-images: false  # MD052
ignores:
  - .github/copilot-instructions.md
  - .windsurf/rules/**
  - .windsurf/workflows/**
