---
config:
  ul-indent: false  # MD007
  line-length: false  # MD013
  no-duplicate-heading: false  # MD024
  reference-links-images: false  # MD052
  no-multiple-blanks: false  # MD012 - Allow multiple consecutive blank lines (for release-please)
  code-block-style: false  # MD046 - Allow indented code blocks in admonitions
  table-column-style: false  # MD060 - Disable table column alignment checks
ignores:
  - .github/copilot-instructions.md
  - .windsurf/rules/**
  - .windsurf/workflows/**
