---
config:
  ul-indent: false  # MD007
  line-length: false  # MD013
  no-duplicate-heading: false  # MD024
  reference-links-images: false  # MD052
ignores:
  - .github/copilot-instructions.md
  - .windsurf/rules/coding-standards.md
  - .windsurf/rules/core-principles.md
  - .windsurf/rules/development-practises.md
  - .windsurf/workflows/fix-specs.md
  - .windsurf/workflows/rubocop.md
  - .windsurf/workflows/update-dependencies.md
