plugins: rubocop-rspec

Metrics/ModuleLength:
  Max: 200
Metrics/MethodLength:
  Max: 15
RSpec/MultipleMemoizedHelpers:
  Max: 20
RSpec/MultipleExpectations:
  Max: 10
RSpec/ExampleLength:
  Max: 20
Layout/LineLength:
  Max: 150
# Ignore tests for now
AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'tests/**/*'
