require: rubocop-rspec

Metrics/ModuleLength:
  Max: 200
Metrics/MethodLength:
  Max: 11
RSpec/MultipleMemoizedHelpers:
  Max: 12
RSpec/MultipleExpectations:
  Max: 10
RSpec/ExampleLength:
  Max: 10
# Ignore tests for now
AllCops:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'tests/**/*'
