services:
  app:
    build: .
    volumes:
      # - .:/app
      - bundle_cache:/usr/local/bundle
      - cookstyle_cache:/app/.cache
      - ./config/settings/local.yml:/app/config/settings/local.yml
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  test:
    extends: app
    volumes:
      - ./spec:/app/spec
      - ./config:/app/config
      - ./lib:/app/lib
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - BUNDLE_APP_CONFIG=/usr/local/bundle
      # Clear GitHub credentials for testing
      - GITHUB_TOKEN=
      - GCR_GITHUB_APP_ID=
      - GCR_GITHUB_APP_INSTALLATION_ID=
      - GCR_GITHUB_APP_PRIVATE_KEY=
    entrypoint: ["bundle", "exec", "rspec"]
    command: []

volumes:
  bundle_cache:
  cookstyle_cache:
