services:
  app:
    build: .
    volumes:
      # - .:/app
      - cookstyle_cache:/app/.cache
      - ./config/settings/local.yml:/app/config/settings/local.yml
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      # - GCR_LOG_FORMAT=json

  test:
    extends: app
    volumes:
      - ./spec:/app/spec
      - ./config:/app/config
      - ./lib:/app/lib
    environment:
      # Clear GitHub credentials for testing
      - GITHUB_TOKEN=
      - GCR_GITHUB_APP_ID=
      - GCR_GITHUB_APP_INSTALLATION_ID=
      - GCR_GITHUB_APP_PRIVATE_KEY=
    entrypoint: ["bundle", "exec", "rspec"]
    command: []

  docs:
    image: ghcr.io/mkdocs/mkdocs:latest
    volumes:
      - ./docs:/docs

volumes:
  bundle_cache:
  cookstyle_cache:
