# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module CookstyleRunner::Git::Settings; end
module CookstyleRunner::RepositoryManager; end
module Git::RepoContext; end
module Rake::DSL; end
