# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Anonymous_Delegator_88; end
module ::Anonymous_Delegator_89; end
module ::Anonymous_Delegator_93; end
module ::Settings; end
module Rake::DSL; end
