---
# Development Environment Configuration
# This file extends default.yml with development-specific settings

# Cache settings adjusted for development
cache_dir: tmp/cookstyle-dev-cache
use_cache: true

# Operational settings for faster development iteration
thread_count: 2
retry_count: 2

owner: sous-chefs
topics:
  - chef-cookbook
filter_repos: [ruby_rbenv]

branch_name: cookstyle/fixes

pr_title: "Cookstyle Fixes"
create_manual_fix_issues: false
default_branch: main
cache_max_age: 7
force_refresh: true

git_name: Dan Webb
git_email: damacus@users.noreply.github.com
