---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: github-cookstyle-runner-sous-chefs-nfs
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            # Mount an NFS volume for the cache directory
            - name: cachedir-nfs
              persistentVolumeClaim:
                claimName: cookstyle-cache-pvc
          containers:
            - name: github-cookstyle-runner
              image: damacus/github-cookstyle-runner:1.3.3
              volumeMounts:
                - name: cachedir-nfs
                  mountPath: /tmp/cookstyle-runner
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: xorimabot-github
                      key: github_token
                - name: GCR_DESTINATION_REPO_OWNER
                  value: sous-chefs
                # Default is already "chef-cookbook" based on the updated entrypoint.sh
                # - name: GCR_DESTINATION_REPO_TOPICS
                #   value: "chef-cookbook"
                # Default is already "automated/cookstyle" based on the updated entrypoint.sh
                # - name: GCR_BRANCH_NAME
                #   value: "automated/cookstyle"
                # Default is already "Automated PR: Cookstyle Changes" based on the updated entrypoint.sh
                # - name: GCR_PULL_REQUEST_TITLE
                #   value: "Automated PR: Cookstyle Changes"
                - name: GCR_GIT_NAME
                  value: "Xorima Bot"
                - name: GCR_GIT_EMAIL
                  value: "xorimabot@avon-lea.co.uk"
                - name: GCR_GIT_USERNAME
                  value: "xorimabot"
                # Default is already "CHANGELOG.md" based on the updated entrypoint.sh
                # - name: GCR_CHANGELOG_LOCATION
                #   value: "CHANGELOG.md"
                # Default is already "## Unreleased" based on the updated entrypoint.sh
                # - name: GCR_CHANGELOG_MARKER
                #   value: "## Unreleased"
                - name: GCR_MANAGE_CHANGELOG
                  value: "1"
          restartPolicy: Never
---
# PVC for the NFS volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cookstyle-cache-pvc
spec:
  accessModes:
    - ReadWriteMany  # NFS supports multiple readers/writers
  resources:
    requests:
      storage: 5Gi  # Request 5GB of storage
  storageClassName: nfs-client  # Must match your cluster's NFS storage class
---
# Example PV configuration (usually created by cluster admin or dynamically provisioned)
# Uncomment and customize if you need to manually create the PV
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cookstyle-cache-pv
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: nfs-client
#   nfs:
#     server: nfs-server.example.com  # Replace with your NFS server
#     path: "/exports/cookstyle-cache"  # Replace with your export path
