---
name: danger

on:
  pull_request:

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Run Danger
        uses: actionshub/danger-rb@main
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
