---
name: Docker Publish
on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Docker tags
        id: tags
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "DOCKER_TAGS=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAGS=latest" >> $GITHUB_ENV
          fi

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: damacus/github-cookstyle-runner
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ env.DOCKER_TAGS }}
